In [1]:
!pip install numpy scipy matplotlib ipython scikit-learn pandas pillow imageio

   ---------------------------------------- 0.0/46.2 MB ? eta -:--:--
   - -------------------------------------- 1.8/46.2 MB 12.6 MB/s eta 0:00:04
   - -------------------------------------- 2.1/46.2 MB 5.6 MB/s eta 0:00:08
   - -------------------------------------- 2.1/46.2 MB 5.6 MB/s eta 0:00:08
   -- ------------------------------------- 2.9/46.2 MB 3.2 MB/s eta 0:00:14
   --- ------------------------------------ 3.9/46.2 MB 3.6 MB/s eta 0:00:12
   ---- ----------------------------------- 5.2/46.2 MB 4.1 MB/s eta 0:00:11
   ----- ---------------------------------- 6.6/46.2 MB 4.3 MB/s eta 0:00:10
   ------- -------------------------------- 8.7/46.2 MB 5.0 MB/s eta 0:00:08
   -------- ------------------------------- 9.7/46.2 MB 5.1 MB/s eta 0:00:08
   --------- ------------------------------ 11.0/46.2 MB 5.1 MB/s eta 0:00:07
   ---------- ----------------------------- 11.8/46.2 MB 5.1 MB/s eta 0:00:07
   ---------- ----------------------------- 12.3/46.2 MB 4.9 MB/s eta 0:00:07
  

In [14]:
# data
# Python 자료구조
# 리스트, 튜플, 딕셔너리, 세트

# 리스트
list2= [2,3,4,5,6]
print(list2[2]) # 3번째 요소 가져오기
print(list2[2:4]) # 3 ~ 4번째 요소 가져오기
list2.append(7) # 가장 마지막에 요소 추가
print(list2)
list2.insert(0,1) # 해당 인덱스에 요소 추가
print(list2)
list2[4] = 500 # 요소 수정
print(list2)
del list2[5] # 요소 지우기
list2.remove(500)
print(list2) # 리스트 길이 반환
print(len(list2))

4
[4, 5]
[2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 500, 6, 7]
[1, 2, 3, 4, 7]
5


In [15]:
# 튜플
# 리스트 대비 추가, 수정, 삭제가 되지 않는다
tuple2 = (2, 3, 4, 5, 6)
print(tuple2[2])     # 튜플 인덱싱
print(tuple2[2 : 4]) # 튜플 슬라이싱
print(len(tuple2))   # 튜플의 길이

4
(4, 5)
5


In [33]:
# 딕셔너리
# key-value 쌍으로 이루어진 자료구조
# {}로 이루어져 있다
# API 통신에 사용된다
dic2 = {
    "이름": "노재웅",
    "나이": 20,
    "mbti": "ISTP",
    "course": ["python","프로젝트"]
    }
print(dic2)

# key를 통해 value 접근
print(dic2["mbti"])
print(dic2.get("나이"))

# 새로운 key-value 쌍 추가
dic2["점심메뉴"] = "돈까스"
print(dic2)

# key를 통해 value 수정
dic2["점심메뉴"] = "짬뽕"
print(dic2)

# 딕셔너리 key-value 삭제
del dic2["나이"]
print(dic2)

# 딕셔너리 모든 key-values 가져오기
print(list(dic2.keys()))
print(list(dic2.values()))
print(list(dic2.items()))

# 딕셔너리 특정 key가 있나요?
print("이름" in dic2)

{'이름': '노재웅', '나이': 20, 'mbti': 'ISTP', 'course': ['python', '프로젝트']}
ISTP
20
{'이름': '노재웅', '나이': 20, 'mbti': 'ISTP', 'course': ['python', '프로젝트'], '점심메뉴': '돈까스'}
{'이름': '노재웅', '나이': 20, 'mbti': 'ISTP', 'course': ['python', '프로젝트'], '점심메뉴': '짬뽕'}
{'이름': '노재웅', 'mbti': 'ISTP', 'course': ['python', '프로젝트'], '점심메뉴': '짬뽕'}
['이름', 'mbti', 'course', '점심메뉴']
['노재웅', 'ISTP', ['python', '프로젝트'], '짬뽕']
[('이름', '노재웅'), ('mbti', 'ISTP'), ('course', ['python', '프로젝트']), ('점심메뉴', '짬뽕')]
True


In [41]:
# 세트
# 중복을 허용하지 않는 자료구조
# 순서가 없다 : 메모리상에 올라갈 때 주솟값이 연속적이지 않다
# {}로 표기하면서 key-value가 없으면 세트
# 중복 제거, 교집합, 합집합, 차집합
set2 = {1,2,3,3,4,5,5,5}
print(set2)

# 중복 제거 용도로 사용
list3 = [1,2,3,3,4,5,5,5]
print("중복 제거 전 :",list3)
list3 = list(set(list3))
print("중복 제거 후 :",list3)

set_A = {1,2,3,4,5}
set_B = {4,5,6,7,8}

# 교집합 (&)
print("교집합 :",set_A & set_B)
# 합집합 (|)
print("합집합 :",set_A | set_B)
# 차집합 (-)
print("차집합 :",set_A - set_B)

{1, 2, 3, 4, 5}
중복 제거 전 : [1, 2, 3, 3, 4, 5, 5, 5]
중복 제거 후 : [1, 2, 3, 4, 5]
교집합 : {4, 5}
합집합 : {1, 2, 3, 4, 5, 6, 7, 8}
차집합 : {1, 2, 3}


In [ ]:
# numpy (Numerical Python)
# 계산 및 데이터 분석 라이브러리
# 다차원배열 (ndarray)
# N-dimensional Array : 벡터 연산을 통해 리스트보다 월등하게 빠르다 ( C언어 기반 )
# 모든 요소에 대해 동시 연산

In [68]:
import time
list_C = list(range(10000000))
list_D = list(range(10000000))
list_result = [0] * 100000000
list_start = time.time()

for i in range(len(list_C)):
    list_result = list_C[i] + list_D[i]
list_end = time.time()
print(f"걸린 시간:{list_end - list_start:.5f}초")

걸린 시간:1.24201초


In [69]:
arr_C = np.arange(10000000)
arr_D = np.arange(10000000)

arr_start = time.time()
arr_result = arr_C + arr_D
arr_end = time.time()

print(f"걸린 시간:{arr_end - arr_start:.5f}초")

걸린 시간:0.02300초


In [59]:
import numpy as np
# as (alias) 별칭 : 해당 라이브러리를 다음과 같이 부르겠다
# 리스트로부터 ndarray 만들기
# ndarray를 nd어레이, 배열
list4 = [1,2,3,4,5]
arr1 = np.array(list4)
print(arr1)

# 2차원 배열 마들기
list5 = [[1,2,3],[4,5,6]]
arr2 = np.array(list5)
print(arr2)

# 배열의 속성 확인하기
# shape
print("arr2의 (행,열):",arr2.shape) # (행, 열)

# ndim
print("arr2의 차원:",arr2.ndim) # 차원

# dtype
print("arr2의 요소 타입:",arr2.dtype) # 배열 요소의 타입

# 특별한 형태의 배열 형성
# 모든 요소가 0 인 배열
zeros_arr = np.zeros((2,3)) # 2행 3열 전부 0
print(zeros_arr)

# 모든 요소가 1인 배열
ones_arr = np.ones((2,3)) # 2행 3열 전부 1
print(ones_arr)

# 특정 범위로 배열 설정
range_arr = np.arange(10) # 10 ~ 9 까지
print(range_arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
arr2의 (행,열): (2, 3)
arr2의 차원: 2
arr2의 요소 타입: int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [100]:
# 배열의 인덱싱 및 슬라이싱
# 리스트의 인덱싱과 슬라이싱과 유사하지만
# 배열에서는 차원별 접근 가능

arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)

# 1) 인덱싱
# 1행 2열의 요소 가져오기
# 인덱스 번호가 0부터 시작하므로 0,1
print("arr3의 1행 2열:",arr3[0,1])

# 2) 슬라이싱
# 2행 2열 ~ 3행 3열
print("arr3의 2행 2열 ~ 3행 3열:\n",arr3[1:, 1:])
# 행만 따졌을 때, 2행 ~ 3행 (인덱스 1부터 인덱스 3미만)
# 열만 따졌을 때, 2행 ~ 3행 (인덱스 1부터 인덱스 3미만)

# 1행의 모든열
print("arr3의 1행의 모든열:\n",arr3[0, 0:3])
# 슬라이싱 시 : 기준 [시작 인덱스: 끝 인덱스], -> 시작 생략 시 처음부터, 끝 생략 시 끝까지

# 3) Boolean 인덱싱★★★
# 특정 조건을 만족하는 요소들만 추출
# arr3 >= 5 해당 결과는 동일한 (행,열)을 가지는 True, False 논리형 배열
print((arr3 > 5).dtype) # 모든 요소가 Boolean 타입
print("arr3 요소 중 5 이상:",arr3[arr3 > 5]) # 해당 Boolean 연산시 Treu만 가져올 수 있다

# arr3의 요소중 짝수만 출력
print("arr3 요소 중 짝수:",arr3[arr3 % 2 == 0])

# 4) 배열 간 연산
arr_A = np.array([[1,2],
                 [3,4]])
arr_B = np.array([[5,6],
                 [7,8]])

# 배열 덧셈
print("배열 덧셈:\n",arr_A + arr_B)
print("배열 뺄셈:\n",arr_A - arr_B)
print("배열 곱셈:\n",arr_A * arr_B)
print("배열 나눗셈:\n",arr_A / arr_B)

# 스칼라 연산
print("배열에 10 더하기:\n",arr_A + 10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3의 1행 2열: 2
arr3의 2행 2열 ~ 3행 3열:
 [[5 6]
 [8 9]]
arr3의 1행의 모든열:
 [1 2 3]
bool
arr3 요소 중 5 이상: [6 7 8 9]
arr3 요소 중 짝수: [2 4 6 8]
배열 덧셈:
 [[ 6  8]
 [10 12]]
배열 뺄셈:
 [[-4 -4]
 [-4 -4]]
배열 곱셈:
 [[ 5 12]
 [21 32]]
배열 나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
배열에 10 더하기:
 [[11 12]
 [13 14]]


In [122]:
# 배열 응용
# 형태 변경 reshape()
arr3.shape # 형태확인

arr4 = np.arange(12) # 0 ~ 11, 1차원 배열
print("원본 배열:",arr4)

arr5 = arr4.reshape(3,4)
print("3헹 4열:\n",arr5)

np.arange(1,5).reshape(2,2)

arr6 = arr4.reshape(2,-1) # 열을 모를 때 -1
print(arr6)

# 기본 통계 함수
print("전체 합계: ",arr5.sum())
print("전체 평균: ",arr5.mean())
print("최댓값:",arr5.max())
print("최솟값:",arr5.min())

# 축(axis)을 이용한 연산
print("각 행의 합계: ",arr5.sum(axis=1)) # 행끼리 연산 (axis =1)
print("각 열의 합계: ",arr5.sum(axis=0)) # 열끼리 연산 (axis =0)

# 난수 생성
# 3 X 3 배열을 0 ~ 사이에서 생성
arr7 = np.random.rand(3,3)
print("랜덤 배열(0~1):\n", arr7)

# 3 X 3 배열을 0 ~ 1 사이에서 생성(단, 표준정규분포를 따라서 )
arr8 = np.random.randn(3,3)
print("표준정규분포(0~1):\n", arr8)

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3헹 4열:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
전체 합계:  66
전체 평균:  5.5
최댓값: 11
최솟값: 0
각 행의 합계:  [ 6 22 38]
각 열의 합계:  [12 15 18 21]
랜덤 배열(0~1):
 [[0.37718119 0.20749476 0.84097679]
 [0.35604637 0.19152683 0.15622866]
 [0.30730391 0.17224904 0.25832771]]
표준정규분포(0~1):
 [[ 0.28911452  0.91011308 -0.50378119]
 [ 0.76323795  0.21514686 -1.0339931 ]
 [ 0.65190193  0.42300609 -0.44539139]]


In [130]:
# python에서 예외 처리
# Error class
# 두 개의 정수를 입력 받아
# 두 번째 정수가 첫 번재 정수의 약수이면
# "약수입니다"
# 아니면 "약수가 아닙니다"

try:
    num1 = int(input("첫 번째 정수 입력:"))
    num2 = int(input("두 번째 정수 입력:"))
    print("약수입니다" if num1 % num2 == 0 else "약수가 아닙니다")

except ZeroDivisionError:
    print("error: 0으로 나눌 수 없습니다")

except ValueError:
    print("error: 숫자를 입력해주세요")

except: # 전체 에러 pass ( 선호하지 않음 )
    print("내가 모르는 에러")
    
finally: # 에러가 발생하든 만든 무조건 진행
    print("프로그램 종료")

첫 번째 정수 입력: 10
두 번째 정수 입력: 0


error: 0으로 나눌 수 없습니다
프로그램 종료


In [138]:
# 전송 Data
# CSV, XML, JSON

# 1) CSV
import csv

# 우리의 workspace 안에 저장
# open(경로,모드)
# 경로는 현재 경로부터 출발 workspace
# 모드 w(write), r(read), a(파일이 없으면 write, 있으면 덮어쓰기)
file = open("member.csv","w", newline="") # newline ->> 마지막 부분 공백 제거
writer = csv.writer(file)
header = ["이름", "나이", "mbti"]
writer.writerow(header)
writer.writerow(["노재웅", 20, "ISTP"])
writer.writerow(["아이유", 30, "INFP"])

file.close()

In [142]:
# csv read
# 개발자라면 open()통해서 통로를 열었다가
# 반드시, close() 통해서 닫아야 한다
# close() 사용하지 않은 이슈를 방지하기 위해
# with ~ open()
with open("member.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

# header를 기준으로 key-value로 구분
dic_list = []
with open("member.csv", "r") as file:
    reader = csv.DictReader(file)
    for row in reader:
        dic_list.append(row)
print(dic_list)

# dic_list안에 "나이" key를 통해서 모든 나이의 총합
age_total = 0
for member in dic_list:
    age_total += int(member["나이"])
print("나이 누적 합:",age_total)

['이름', '나이', 'mbti']
['노재웅', '20', 'ISTP']
['아이유', '30', 'INFP']
[{'이름': '노재웅', '나이': '20', 'mbti': 'ISTP'}, {'이름': '아이유', '나이': '30', 'mbti': 'INFP'}]
나이 누적 합: 50


In [144]:
!curl -L https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv -o pokemon.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 44028  100 44028    0     0  98601      0 --:--:-- --:--:-- --:--:-- 98601


In [167]:
pokemon_list = []
with open("pokemon.csv","r", encoding="UTF-8") as file:
    reader = csv.DictReader(file)
    for row in reader:
        pokemon_list.append(row)

pokemon_list[1]

# 1세대 포켓몬의 객체치(total)의 합

total_gener = 0
count_gener = 0
total = 0

for i in range(len(pokemon_list)):
    if pokemon_list[i]["Generation"] == "1":
        total_gener += int(pokemon_list[i]["Total"])
        count_gener += 1
    total = total_gener / count_gener
print("1세대 포켓몬 Total 평균: ", total)

1세대 포켓몬 Total 평균:  426.81325301204816


In [168]:
# XML 재밌는 실습

import requests
MY_API_KEY = "7077141e402b34395ff1bda2f711ff5c"
date = "20250907"
url_movie = f"https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.xml?key={MY_API_KEY}&targetDt={date}"

response = requests.get(url_movie)
response

<Response [200]>

In [170]:
# 응답 객체를 다루는 3가지 방법
# response.text # 문자열
# response.content # byte (파일, 이미지)
# response.json() # json (dictionary)
result = response.text
result

'<?xml version="1.0" encoding="utf-8" standalone="yes"?><boxOfficeResult><boxofficeType>일별 박스오피스</boxofficeType><showRange>20250907~20250907</showRange><dailyBoxOfficeList><dailyBoxOffice><rnum>1</rnum><rank>1</rank><rankInten>0</rankInten><rankOldAndNew>OLD</rankOldAndNew><movieCd>20253289</movieCd><movieNm>극장판 귀멸의 칼날: 무한성편</movieNm><openDt>2025-08-22</openDt><salesAmt>1921616300</salesAmt><salesShare>46.8</salesShare><salesInten>-434451800</salesInten><salesChange>-18.4</salesChange><salesAcc>42762691970</salesAcc><audiCnt>179724</audiCnt><audiInten>-39259</audiInten><audiChange>-17.9</audiChange><audiAcc>3957581</audiAcc><scrnCnt>1532</scrnCnt><showCnt>5142</showCnt></dailyBoxOffice><dailyBoxOffice><rnum>2</rnum><rank>2</rank><rankInten>0</rankInten><rankOldAndNew>OLD</rankOldAndNew><movieCd>20256702</movieCd><movieNm>컨저링: 마지막 의식</movieNm><openDt>2025-09-03</openDt><salesAmt>562126020</salesAmt><salesShare>13.7</salesShare><salesInten>-188454210</salesInten><salesChange>-25.1</sales

In [182]:
import xml.etree.ElementTree as ET
root = ET.fromstring(result)

# find("태그 이름") -> <태그 이름>내용</태그 이름>
# findall("태그 이름") => [<태그 이름>내용</태그 이름>, <태그 이름>내용</태그 이름>, ...]
# root.findall(".//movieNm")[1].text # .// 하위 태그 전부 탐색

for movie in root.findall(".//dailyBoxOffice"):
    # rank, movieNm, audiCnt, audiAcc
    rank = movie.find("rank").text
    movieNm = movie.find("movieNm").text
    audiCnt = movie.find("audiCnt").text
    audiAcc = movie.find("audiAcc").text
    print(f"{rank}위 : {movieNm}({audiCnt}명/{audiAcc}명)")

1위 : 극장판 귀멸의 칼날: 무한성편(179724명/3957581명)
2위 : 컨저링: 마지막 의식(54256명/233111명)
3위 : 살인자 리포트(53241명/152738명)
4위 : 좀비딸(32982명/5498890명)
5위 : F1 더 무비(31657명/4914286명)
6위 : 첫사랑 엔딩(10512명/109643명)
7위 : 아기돼지 3형제: 도넛별 대모험(5097명/13657명)
8위 : 투게더(4325명/29036명)
9위 : 긴키 지방의 어느 장소에 대하여(2957명/268545명)
10위 : 킹 오브 킹스(1993명/1302743명)


In [194]:
# Pandas
# 2차원 데이터(테이블 형태)를 다루는 데 특화된 라이브러리
# 2차원 데이터 : DataFrame
# 1차원 데이터 : series
import pandas as pd

# 인덱스를 따로 설정하지 않는다 면 0부터 차례로 정해진다
# pandas의 series, DataFrame은 보통 그냥 출력
s1 = pd.Series([10,20,30,40], index=['a','b','c','d'])
s1['c'] # 시리즈의 인덱스 'c' 가져오기

# DataFrame 다루기
data = {
    "Name" : ["노재웅","김한나","김정우","류이현"],
    "Age" : [20, 21, 23, 25],
    "MBTI" : ["ENFJ","INFP","ESTP","ISTJ"]
}

df = pd.DataFrame(data)
df

Name  Age  MBTI
0  노재웅   20  ENFJ
1  김한나   21  INFP
2  김정우   23  ESTP
3  류이현   25  ISTJ

In [197]:
# csv로부터 DataFrame 만들기
df_pokemon = pd.read_csv("pokemon.csv", encoding="UTF=8")
df_pokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [206]:
df_pokemon.head() # 상위 5개 데이터 출력
df_pokemon.head(2) # 상위 n개 데이터 출력 (2)
df_pokemon.tail() # 하위 5개 데이터 출력
df_pokemon.tail(2) # 하위 n개 데이터 출력 (2)

#                Name   Type 1 Type 2  Total  HP  Attack  Defense  \
798  720  HoopaHoopa Unbound  Psychic   Dark    680  80     160       60   
799  721           Volcanion     Fire  Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
798      170      130     80           6       True  
799      130       90     70           6       True

In [207]:
df_pokemon.info() # df의 전반적인 정보 ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64 
 5   HP          800 non-null    int64 
 6   Attack      800 non-null    int64 
 7   Defense     800 non-null    int64 
 8   Sp. Atk     800 non-null    int64 
 9   Sp. Def     800 non-null    int64 
 10  Speed       800 non-null    int64 
 11  Generation  800 non-null    int64 
 12  Legendary   800 non-null    bool  
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB


In [208]:
df_pokemon.describe() # df의 통계적 정보

#      Total          HP      Attack     Defense     Sp. Atk  \
count  800.000000  800.00000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750  435.10250   69.258750   79.001250   73.842500   72.820000   
std    208.343798  119.96304   25.534669   32.457366   31.183501   32.722294   
min      1.000000  180.00000    1.000000    5.000000    5.000000   10.000000   
25%    184.750000  330.00000   50.000000   55.000000   50.000000   49.750000   
50%    364.500000  450.00000   65.000000   75.000000   70.000000   65.000000   
75%    539.250000  515.00000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.00000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  800.000000  800.000000   800.00000  
mean    71.902500   68.277500     3.32375  
std     27.828916   29.060474     1.66129  
min     20.000000    5.000000     1.00000  
25%     50.000000   45.000000     2.00000  
50%     70.000000   65.000000     3.00000  
75%     90.000000   90.000000     5.00000  
max    230.000000  180.000000     6.00000

In [209]:
df_pokemon.dtypes # df의 요소별 타입 정보

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [251]:
df_pokemon.sample() # df중 랜덤 데이터 1개 출력
df_pokemon.sample(3) # df중 랜덤 데이터 n개 출력 (3)

#     Name   Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
586  527   Woobat  Psychic  Flying    313  55      45       43       55   
578  519   Pidove   Normal  Flying    264  50      55       50       36   
58    53  Persian   Normal     NaN    440  65      70       60       65   

     Sp. Def  Speed  Generation  Legendary  
586       43     72           5      False  
578       30     43           5      False  
58        65    115           1      False

In [271]:
# 포켓몬의 df 활요해서
# 데이터 가져오기
# 해당 열 가져오기 -> Series로 반환가능
# 데이터프레임명["컬럼명"] or 데이터프레임명.컬럼명
df_pokemon["Name"]
df_pokemon.Name

# 해당 행 가져오기
# loc(Location)
# 데이터프레임명.loc[인덱스명] #인덱스 번호아님
df_pokemon.loc[0]

# iloc(integer Location)
# 데이터프레임명.iloc[인덱스번호]
df_pokemon.iloc[0]

# 행, 열 동시에 접근
# 첫 번째 포켓몬의이름
df_pokemon.loc[0, "Name"] # [인덱스명:0, 컬럼명:Name]
df_pokemon.iloc[0,1] # [인덱스 번호:0, 컴럼 인덱스:1]

# 슬라이싱 -> 인덱싱 부분에 ":" 쓰기
# 3번째 포켓몬부터 10번째 포켓몬까지
df_pokemon.loc[2:9] # 슬라이싱 시 인덱스명이기 때문에 둘 다 포함( both included )
df_pokemon.iloc[2:10] # 정수형이기 때문에 끝 인덱스 미만

df_pokemon.loc[2:9,"Name": "Defense"] # 3번째 ~ 10번째까지 "Name" ~ "Defense"
df_pokemon.iloc[2:10, 1:8] # 3번째 ~ 10(인덱스 11미만)번째까지  컬럼 인덱스 1 ~ 7

Name Type 1  Type 2  Total  HP  Attack  Defense
2                   Venusaur  Grass  Poison    525  80      82       83
3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4                 Charmander   Fire     NaN    309  39      52       43
5                 Charmeleon   Fire     NaN    405  58      64       58
6                  Charizard   Fire  Flying    534  78      84       78
7  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
8  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
9                   Squirtle  Water     NaN    314  44      48       65

In [277]:
# Boolean Indexing
df_pokemon[df_pokemon["Total"] >= 500] # Total이 500이상인 데이터만 추출
df_pokemon[(df_pokemon["Total"] >= 500) & (df_pokemon["Generation"] == 1)]

#                       Name    Type 1    Type 2  Total   HP  Attack  \
2      3                   Venusaur     Grass    Poison    525   80      82   
3      3      VenusaurMega Venusaur     Grass    Poison    625   80     100   
6      6                  Charizard      Fire    Flying    534   78      84   
7      6  CharizardMega Charizard X      Fire    Dragon    634   78     130   
8      6  CharizardMega Charizard Y      Fire    Flying    634   78     104   
11     9                  Blastoise     Water       NaN    530   79      83   
12     9    BlastoiseMega Blastoise     Water       NaN    630   79     103   
23    18        PidgeotMega Pidgeot    Normal    Flying    579   83      80   
36    31                  Nidoqueen    Poison    Ground    505   90      92   
39    34                   Nidoking    Poison    Ground    505   81     102   
43    38                  Ninetales      Fire       NaN    505   73      76   
60    55                    Golduck     Water       NaN    500   80      82   
64    59                   Arcanine      Fire       NaN    555   90     110   
67    62                  Poliwrath     Water  Fighting    510   90      95   
70    65                   Alakazam   Psychic       NaN    500   55      50   
71    65      AlakazamMega Alakazam   Psychic       NaN    590   55      50   
74    68                    Machamp  Fighting       NaN    505   90     130   
79    73                 Tentacruel     Water    Poison    515   80      70   
84    78                   Rapidash      Fire       NaN    500   65     100   
87    80        SlowbroMega Slowbro     Water   Psychic    590   95      75   
96    89                        Muk    Poison       NaN    500  105     105   
98    91                   Cloyster     Water       Ice    525   50      95   
101   94                     Gengar     Ghost    Poison    500   60      65   
102   94          GengarMega Gengar     Ghost    Poison    600   60      65   
111  103                  Exeggutor     Grass   Psychic    520   95      95   
124  115  KangaskhanMega Kangaskhan    Normal       NaN    590  105     125   
130  121                    Starmie     Water   Psychic    520   60      75   
132  123                    Scyther       Bug    Flying    500   70     110   
136  127                     Pinsir       Bug       NaN    500   65     125   
137  127          PinsirMega Pinsir       Bug    Flying    600   65     155   
140  130                   Gyarados     Water    Flying    540   95     125   
141  130      GyaradosMega Gyarados     Water      Dark    640   95     155   
142  131                     Lapras     Water       Ice    535  130      85   
145  134                   Vaporeon     Water       NaN    525  130      65   
146  135                    Jolteon  Electric       NaN    525   65      65   
147  136                    Flareon      Fire       NaN    525   65     130   
153  142                 Aerodactyl      Rock    Flying    515   80     105   
154  142  AerodactylMega Aerodactyl      Rock    Flying    615   80     135   
155  143                    Snorlax    Normal       NaN    540  160     110   
156  144                   Articuno       Ice    Flying    580   90      85   
157  145                     Zapdos  Electric    Flying    580   90      90   
158  146                    Moltres      Fire    Flying    580   90     100   
161  149                  Dragonite    Dragon    Flying    600   91     134   
162  150                     Mewtwo   Psychic       NaN    680  106     110   
163  150        MewtwoMega Mewtwo X   Psychic  Fighting    780  106     190   
164  150        MewtwoMega Mewtwo Y   Psychic       NaN    780  106     150   
165  151                        Mew   Psychic       NaN    600  100     100   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
2         83      100      100     80           1      False  
3        123      122      120     80           1      False  
6         78      109    